### ISSUE TITLE
DEBUG窗口会把模板里的`/r`去掉

### ISSUE THREAD

**Issue by WEGFan** [gejun123456/easyCode-MybatisCodeHelper#21]
版本：1.3.9+232

![图片](https://github.com/user-attachments/assets/ee3006d0-d425-41dc-9d4c-e8cd133acfa0)

应该是这行代码导致的，不知道为什么这么写，看后面的代码感觉这里应该是`\r`才对

https://github.com/gejun123456/easyCode-MybatisCodeHelper/blob/199f784557179a073a65a653b9b04e70521b7c9e/src/main/java/com/bruce/plugin/scratch/EasyCodeNotificationPanel.java#L374

**Comment by gejun123456** [comment]
对的，插件的问题，感谢反馈

**Comment by WEGFan** [comment]
1.4.0+232已修复
